---
title: "Blood Chemistry Analysis \n Buzzard, Goshawk and Red Kite"
author: "Tony Rinaud"
date: "03/03/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=F}

# Loading required packages

library(ggsci)
library(EnvStats)
library(plotly)
library(patchwork)
library(RColorBrewer)
library(chron)
library(RVAideMemoire)
library(ade4)
library(ggcorrplot)
library(vegan)
require(FactoMineR)
require(factoextra)
require(ggplot2)
require(tidyr)
require(dplyr)
require(MASS)
require(reshape2)
require(cowplot)
library(patchwork)
library(EnvStats)
library(ggrepel)
library(Hmisc)

# Routine clean-up upon start

rm(list=ls())
```

# PCA

```{r}
# Set the working directory

setwd("C://Users/Tony/Documents/Phd Bielefeld/Data manip/Chemistry_blood/BloodChemistryR/data/")

# Load the raw file, blood chemistry (update with NA instead of blanks)

bloody=read.csv2('raw_18.09.20.csv', h=T, dec=',')

# Setting classes

bloody$Species=as.factor(bloody$Species)
bloody$Sex=as.factor(bloody$Sex)
bloody$Mass=as.numeric(bloody$Mass)

# Creating variable for Infection classes No / Low / High Infection

bloody$infectionclass=NA

for (i in 1:length(bloody$Infection_intensity)){
  if(bloody$Infection_intensity[i]==0){bloody$infectionclass[i]="No infection"}
  if(bloody$Infection_intensity[i] %in% c(1,2)){bloody$infectionclass[i]="Low infection"}
  if(bloody$Infection_intensity[i] %in% c(3,4)){bloody$infectionclass[i]="High infection"}
} 

bloody$infectionclass=as.factor(bloody$infectionclass)

# Selecting the variable to be used in the pca

bloodypca=bloody[,c(10:16,19:28)]

# Scaling the variables

bloodypca=scale(bloodypca)

# Removing NAs for pca

bloodypca=na.omit(bloodypca)

# Correlation plot between explanatory variables

ggcorrplot(cor(bloodypca), p.mat = cor_pmat(bloodypca), hc.order=TRUE, type='lower')

# Function circular plot

circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
  r = diameter / 2
  tt <- seq(0,2*pi,length.out = npoints)
  xx <- center[1] + r * cos(tt)
  yy <- center[2] + r * sin(tt)
  return(data.frame(x = xx, y = yy))
}

circ <- circleFun(c(0,0),2,npoints = 500)

# PCA  (cf https://tem11010.github.io/Plotting-PCAs/)

PCAblood=PCA(bloodypca)

plot.PCA(PCAblood)

pc1=unlist(PCAblood$ind$coord[, 1], recursive = T,use.names = T)
pc2=unlist(PCAblood$ind$coord[, 2], recursive = T,use.names = T)

coords=data.frame(pc1,pc2)

pca.vars <- PCAblood$var$coord %>% data.frame

pca.vars$vars <- rownames(pca.vars)

pca.vars.m <- melt(pca.vars, id.vars = "vars")

# Plot PCA variables correlation

vars.p <-  ggplot() +
               geom_path(data = circ,aes(x,y), lty = 2, color = "grey", alpha = 0.7)+
               geom_hline(yintercept = 0, lty = 2, color = "grey", alpha = 0.9)+
               geom_vline(xintercept = 0, lty = 2, color = "grey", alpha = 0.9)+
               geom_segment(data = pca.vars, aes(x = 0, xend = Dim.1, y = 0, yend = Dim.2),
                            arrow = arrow(length = unit(0.025, "npc"), type = "open"), 
                            lwd = 1)+ 
              geom_text_repel(data = pca.vars, 
                        aes(x = Dim.1*1.15, y =  Dim.2*1.15, 
                            label = row.names(pca.vars)), 
                            check_overlap = F, size = 5)+
              xlab("PC 1")+ 
              ylab("PC 2")+
              coord_equal()+
              theme_minimal()+
              theme(panel.grid = element_blank(), 
                    panel.border = element_rect(fill= "transparent"))

vars.p
```

## Plot PCA individual with species labels

```{r}

indplot=ggplot(data=coords, aes(x = pc1, y = pc2, color=bloody$Species))+
  geom_point(color='black',size=4.5)+
  geom_point(size=4)+
  labs(x="PC1 (16.89%)", y="PC2 (14.98%)",color = "Species")+
  geom_hline(yintercept = 0, lty = 2)+
  geom_vline(xintercept = 0, lty = 2)+
  scale_color_manual(values=c("#427EF6", "#7C3918", "#FF9100"))+
  theme_classic()+
  theme(legend.position = "bottom", legend.text = element_text(size=12),axis.title=element_text(size=14), axis.text=element_text(size=12), plot.title = element_text(hjust = 0.5, face="bold"), panel.border = element_rect(fill= "transparent"))+
  stat_ellipse(geom="polygon", aes(fill = bloody$Species),alpha = 0.2, show.legend = FALSE, level = 0.95)

```

## Plot PCA individuals with infection intensity labels 

```{r}

indinfplot=ggplot(data=coords, aes(x = pc1, y = pc2, color=as.factor(bloody$infectionclass))) +
  geom_point(color='black',size=4.5)+
  geom_point(size=4)+
  labs(x="PC1 (16.89%)", y="PC2 (14.98%)",color = "Infection intensity")+
  geom_hline(yintercept = 0, lty = 2)+
  geom_vline(xintercept = 0, lty = 2)+
  scale_color_manual(values=c("#A50F15","#FB6A4A","#FCAE91"))+
  theme_classic()+
  theme(legend.position = "bottom", legend.text = element_text(size=12),axis.title=element_text(size=14), axis.text=element_text(size=12), plot.title = element_text(hjust = 0.5, face="bold"), panel.border = element_rect(fill= "transparent"))+
  stat_ellipse(geom="polygon", aes(color = as.factor(bloody$infectionclass)), alpha = 0.05, show.legend = FALSE, level = 0.95, size=0.7)

indplot/indinfplot|vars.p + plot_layout(ncol=1)

```

# LDA

## LDA constrained by Species

```{r}

# Checking normal multivariate distribution

par(mfrow = c(2, 2))
for(i in dimnames(bloodypca)[[2]]) {
  qqnorm(bloodypca[,i]); qqline(bloodypca[,i], col = 3)
}

# Checking homogeneity of the matrix variance - covariance

anova(betadisper(dist(bloodypca),bloody$Species))

heplots::covEllipses(diabetes[,1:8], 
                     diabetes$Outcome, 
                     fill = TRUE, 
                     pooled = FALSE, 
                     col = c("blue", "red"), 
                     variables = c(1:5, 8), 
                     fill.alpha = 0.05)

# LDA constrained by species

ldaSpecies=lda(bloodypca, bloody$Species, CV=T)   #  CV=T 

# Cross-validation of the dataset

tableclass=base::table(bloody$Species, ldaSpecies$class)

MVA.cv(bloodypca, bloody$Species, model="LDA", scale=T)

```

```{r}
par(mfrow=c(1,2))
MVA.plot(ldaSpecies,fac=bloody$Species,xlab="Axis 1", ylab="Axis 2", col=c("#427EF6", "#7C3918", "#FF9100"),legend=F, legend.cex=0.5, legend.pos="topleft", legend.lab=c("Accipiter gentilis", "Buteo buteo","Milvus milvus"))
MVA.plot(ldaSpecies,"corr", xlab="Axis 1", ylab="Axis 2")

```

## LDA constrained by Infection class

```{r}

# Checking normal multivariate distribution

qqPlot(bloodypca[,1])

anova(betadisper(dist(bloodypca),bloody$infectionclass))

ldaInfclass=lda(bloodypca, bloody$infectionclass)   #  CV=T

#tableclass=base::table(catptPGR, ldaPGR$class)

MVA.cv(bloodypca, bloody$infectionclass, model="LDA", scale=T)

par(mfrow=c(1,2))
MVA.plot(ldaInfclass,fac=bloody$infectionclass,xlab="Axis 1", ylab="Axis 2", col=c("#427EF6", "#7C3918", "#FF9100"),legend=F, legend.cex=0.9, legend.pos="topleft", legend.lab=c("High Infection", "Low Infection","No Infection"))
MVA.plot(ldaInfclass,"corr", xlab="Axis 1", ylab="Axis 2")

```

## LDA constrained by Age classes Three weeks / A month / A month+

```{r}

bloody$AgeClass=NA

for (i in 1:length(bloody$Age)){
  if(bloody$Age[i] <= 25){bloody$AgeClass[i]="Three weeks"}
  if(bloody$Age[i] > 25 & bloody$Age[i] <= 30){bloody$AgeClass[i]="A month"}
  if(bloody$Age[i] > 30){bloody$AgeClass[i]="Over a month"}
} 

bloody$AgeClass=as.factor(bloody$AgeClass)

#LDA constrained by age

qqPlot(bloodypca[,1])

anova(betadisper(dist(bloodypca),bloody$AgeClass))

ldaAge=lda(bloodypca, bloody$AgeClass)   #  CV=T

tableclass=base::table(bloody$AgeClass, ldaAge$class)

MVA.cv(bloodypca, bloody$infectionclass,model="LDA", scale=T)

par(mfrow=c(1,2))
MVA.plot(ldaAge,fac=bloody$AgeClass,xlab="Axis 1", ylab="Axis 2",col=c("#427EF6", "#7C3918", "#FF9100"), legend=F, legend.cex=0.9, legend.pos="topleft")
MVA.plot(ldaAge,"corr", xlab="Axis 1", ylab="Axis 2")

# mod=lm(as.matrix(bvPGR)~catptPGR)
# 
# plotresid(mod)
# 
# Manova(mod, test.statistic="Wilks")
# 
# summary(mod)
```
## LDA constrained by Body condition classes Low / Average / High

```{r} 

bloody$Body_condition=residuals(lm(bloody$Mass~bloody$Wing))

bloody$Bcond_Class=NA

for (i in 1:length(bloody$Body_condition)){
  if(bloody$Body_condition[i] <= -235.1){bloody$Bcond_Class[i]="Low"}
  if(bloody$Body_condition[i] > -48.5 & bloody$Body_condition[i] <= 2.44){bloody$Bcond_Class[i]="Average"}
  if(bloody$Body_condition[i] > 52.2){bloody$Bcond_Class[i]="High"}
} 

bloody$Bcond_Class=as.factor(bloody$Bcond_Class)

#LDA constrained by body condition

qqPlot(bloodypca[,1])

anova(betadisper(dist(bloodypca),bloody$Bcond_Class))

ldaBcond_Class=lda(bloodypca, bloody$Bcond_Class)   #  CV=T

#tableclass=base::table(catptPGR, ldaPGR$class)

# MVA.cv(bloodypca, bloody$infectionclass,model="LDA")

par(mfrow=c(1,2))
MVA.plot(ldaBcond_Class,fac=bloody$Bcond_Class,xlab="Axis 1", ylab="Axis 2",col=c("#427EF6", "#7C3918", "#FF9100"), legend=F, legend.cex=0.9, legend.pos="topleft")
MVA.plot(ldaBcond_Class,"corr", xlab="Axis 1", ylab="Axis 2")

# mod=lm(as.matrix(bvPGR)~catptPGR)
# 
# plotresid(mod)
# 
# Manova(mod, test.statistic="Wilks")
# 
# summary(mod)

```